version: '3.3'

services:
  web:
    build: .  # Build the image using your Dockerfile in the current directory
    ports:
      - "80:80"  # Map container's port 80 to host's port 80
    volumes:
      - /mnt/newsite:/usr/local/apache2/htdocs/  # Mount the directory containing your website files to Apache's document root
    restart: always
