version: '3.3'

services:
  web:
    build: .  # This will build from the Dockerfile in the current directory
    ports:
      - "80:80"  # Map container's port 80 to host's port 8082
    volumes:
      - ./mnt/:/usr/local/apache2/htdocs/  # Mount website files to Apache's document root
    restart: always
